#!/usr/bin/env bash
# This script return nginx web page with or withour nginx running
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep "nginx" | head -1)"
