#!/usr/bin/env bash
# This script dipslay number from 1 to 100 and including FizzBuzz when the number is multiply by 3 and 5
i=1
while [ $i -le 100 ]
do
if (( "$i" % 3 && "$i" % 5 == 0))
then
	echo "FizzBuzz"
elif (( "$i" % 3 == 0 ))
then
	echo "Fizz"
elif (( "$i" % 5 == 0 ))
then
	echo "Buzz"
else
	echo "$i"
fi
((i++))
done
