#!/usr/bin/env bash
# This script print Best School using the while loop and at 9th line it should display Hi
i=1
while [ $i -lt 10 ]
do
	echo "Best School"
	((i++))
if [ $i -eq 9 ]
then
	echo "Hi"
fi
done
