#!/usr/bin/env bash
# This script print Best School 10 times at the 4th line it should display bad luck and 7th line good luck
i=0
while [ $i -lt 10 ]
do
	((i++))
if [ $i == 4 ]
then
	echo "bad luck"
elif [ $i -eq 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
done
