#!/usr/bin/env bash
# This script display number from 1 to 20 and at 4th line it should display bad luck from China and at 9th line it should display bad luck from Japan and at 17th line it should display bad luck from Itay.
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
