#!/usr/bin/env bash
#This script run 100-fix_in_7_lines_or_less
#This script include 8 lines
sed -i "s/Listen 8080/#Listen 8080/g" /etc/apache2/ports.conf
sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -1 apache2
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
